name: PR Preview Publish

on:
  workflow_run:
    workflows: ['PR Preview Build']
    types: [completed]

permissions:
  contents: write
  pages: write
  pull-requests: write
  actions: read
  deployments: write
  issues: write

jobs:
  publish:
    uses: Archetipo95/storybook-github-pages/.github/workflows/pr-preview-publish.yml@v1.9.8
    with:
      workflow_run_id: ${{ github.event.workflow_run.id }}
    secrets: inherit
