name: PR Preview Cleanup

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write
  pages: write
  deployments: write

jobs:
  cleanup:
    uses: Archetipo95/storybook-github-pages/.github/workflows/pr-preview-cleanup.yml@v1.9.1
    secrets: inherit
