name: PR Preview Cleanup

on:
  pull_request_target:
    types: [closed]

concurrency:
  group: storybook-pages-${{ github.repository }}
  cancel-in-progress: false

permissions:
  contents: write
  pages: write

jobs:
  cleanup:
    uses: Archetipo95/storybook-github-pages/.github/workflows/pr-preview-cleanup.yml@v1
    secrets: inherit
